### ISSUE TITLE
Enable AP video live embeds (JW Player)

### ISSUE THREAD

**Issue by mileswwatkins** [nprapps/liveblog#35]
We'll need to check whether JW Player embeds work, and if not then investigate that functionality. Asking Arnie for an example AP video embed to use for testing.

**Comment by mileswwatkins** [comment]
> There is one about half way down this page: https://www.npr.org/2018/07/25/631989026/pompeo-to-face-lawmakers-after-trump-summits-with-foreign-leaders-raise-question
> It presents a slate with a line drawing of the capitol when you scroll by it.

**Comment by freejoe76** [comment]
The https://www.npr.org/2018/07/25/631989026/pompeo-to-face-lawmakers-after-trump-summits-with-foreign-leaders-raise-question JW embed currently works (on handheld and desktop).

I'm going to figure out the embed code and test it on our current liveblog test to make sure it works in a liveblog situation.

**Comment by freejoe76** [comment]
@mileswwatkins is this ticket about writing a shortcode that, given an asset ID, renders the markup necessary for an AP live video embed? I looked through the existing shortcodes in the liveblog repo (`templates/shortcodes`) and we don't have one for the AP.

This is the rendered markup on the example you linked to above, for reference.

```html
<div id="res632359144" class="bucketwrap video npr-video  large">
<div class="bucket">
<div class="graphicwrapper">
  <div id="slideshow632359144"></div>
<div id='jwPlayer632359144' data-jwplayer='{"skinSource":"https:\/\/s.npr.org\/templates\/javascript\/jwplayer\/skins\/npr.css","flashPlayer":"https:\/\/media.npr.org\/templates\/javascript\/jwplayer\/jwplayer.flash.swf","width":"100%","height":"100%","isLive":false,"image":"https:\/\/media.npr.org\/assets\/img\/2017\/12\/12\/npr-whitehouse_wide-0e8a6b67bd1cfc5c7fa324f3ac5c09095cfa8f94-s800-c85.jpg","primary":"html5","sources":[{"file":"https:\/\/nprsxsw-lh.akamaihd.net\/i\/247_nprvideo_1@194755\/master.m3u8","label":null,"type":"hls"}],"tracks":[],"videoPrerollAdUrl":"https:\/\/pubads.g.doubleclick.net\/gampad\/ads?env=vp&gdfp_req=1&impl=s&unviewed_position_start=1&output=vast&iu=%2F6735%2Fn6735.NPR%2FNews_Politics&sz=400x300&correlator=1942388124&cust_params=testserver%3Dfalse%26storyId%3D631989026%26agg%3DArray","shareUrl":"https:\/\/www.npr.org\/2018\/07\/25\/631989026\/pompeo-to-face-lawmakers-after-trump-summits-with-foreign-leaders-raise-question","embedLink":"https:\/\/www.npr.org\/templates\/event\/embeddedVideo.php?storyId=631989026&mediaId=632359144"}'>
  </div>
```

**Comment by alykat** [comment]
It's a bit buried, but if you click "play" on the video, you can access the share tools, which include embed code. I think we'd want to use that code (but set up so that it stretches / works responsively) as the basis for what we use in the liveblog.

```
<iframe width="600" height="338" src="https://www.npr.org/templates/event/embeddedVideo.php?storyId=631989026&mediaId=632359144" frameborder="0" scrolling="no"></iframe>
```

**Comment by mileswwatkins** [comment]
Hmm, is there no way to insert HTML/`iframe` code raw? Or @alykat is there a back-door way to insert HTML/`iframe` into a liveblog post?

Otherwise, @freejoe76, we will need to add a way to insert the AP video feed into the liveblog, _probably_ via a shortcode.

**Comment by alykat** [comment]
I wouldn't work from the markup on the Seamus page — I'd start from that `iframe`. But I don't know if you can arbitrarily insert HTML in the liveblog. Worth testing.

**Comment by freejoe76** [comment]
What we're talking about doing here is pretty similar to implementing cross-site-scripting on an app, which I wasn't able to do.

Putting together a shortcode for a generic iframe is the way forward here, for security reasons we may want to consider a domain whitelist for the iframe'd URLs.

**Comment by freejoe76** [comment]
Okay after talking with Miles I'm going forward on an AP video-specific shortcode, it will be tracked in a branch (to come) named feature/35-ap-video-shortcode

**Comment by freejoe76** [comment]
Related: #36

**Comment by freejoe76** [comment]
After reading the eclipse liveblog (for https://github.com/nprapps/elections18-graphics/issues/7 ), I realized this issue also involves updating the Google Docs add-on that guides shortcode additions (explained in more detail here https://docs.google.com/document/d/1UhahzMqFfYJDNoETCeYgJlAJVC4R-mnpPA-8Vfh3jYs )

**Comment by freejoe76** [comment]
Update: The shortcode renders the markup on localhost!

![screen shot 2018-08-29 at 11 15 40 am](https://user-images.githubusercontent.com/125554/44803925-0fd9e500-ab7d-11e8-8985-c6c1a6d9d8f3.png)

-->

![screen shot 2018-08-29 at 11 16 08 am](https://user-images.githubusercontent.com/125554/44803933-15cfc600-ab7d-11e8-8feb-1fabbab94ef7.png)

**Comment by freejoe76** [comment]
The video now renders, but 
![screen shot 2018-08-29 at 11 55 19 am](https://user-images.githubusercontent.com/125554/44805866-95ac5f00-ab82-11e8-9212-32725f21f174.png)
it needs some styling.

**Comment by freejoe76** [comment]
Styling done. Note that the embedded video asset we're testing against, https://content.jwplatform.com/players/7wkxa1LV-5qkQag5F.html , does not render a mobile-friendly view on handheld widths.

![screen shot 2018-08-29 at 12 12 58 pm](https://user-images.githubusercontent.com/125554/44806710-e91fac80-ab84-11e8-979f-92aebbe23f76.png)

**Comment by freejoe76** [comment]
Notes:

1. Care will need to be taken to make sure the responsive player is the player that's chosen for the livestream in the JW player admin. The player id is communicated along with the video id in the URL, for reference, separated by a hyphen (example: https://content.jwplatform.com/players/b9NCLhTb-vF7GOmpr.html )

2. 16:9 is the aspect ratio for AP video livestreams.

**Comment by freejoe76** [comment]
Note that I did what appeared to be required in https://github.com/nprapps/liveblog-addon to promote the addon code to production: `fab development gs.upsert`.

That command appeared to successfully execute. However, the addon in the google doc I was testing against (which had been installed prior to the update) did not show the new version of the code (I know this because I expected to see an option in the sidebar for AP Livestream, that option was not there).

I'm going to try uninstalling the addon and installing it again.

**Comment by freejoe76** [comment]
Information from Juan (who is on vacation through the 10th):

>>>After testing the new code, We manually copied the modified code into the template code that we then copied for the doc.

We did not use The deploy as an add-on since it require us to create a google developer profile and if I remember correctly

**Comment by freejoe76** [comment]
Update: I tried copy and pasting the production code that was new from the drive's google_apps_scripts/production/LiveblogAddon (which was what was being updated with `fab production gs.upsert`) into the scripts at google_apps_scripts/production/liveblog/liveblog, and then refreshing the test Google Doc, and that did not do anything.

I need more detail from Juan about what he means by "We manually copied the modified code into the template code that we then copied for the doc," I'll ask him for that, note that he's on vacation until Tuesday.

**Comment by freejoe76** [comment]
Update: Miles helped show me the way. Code can manually be copy and pasted into the latest liveblog Google Doc if you go to the Tools --> Script Editor menu option.

After you do that, copy and paste the code that has changed in each of the documents that has changed. In my case, for the edits to the embed sidebar, that meant updating embed.gs, embed_sidebar.html and embed_sidebar_js.html.

Note that the script editor saves every change of every file in its version log, and you can restore should something go wrong.

**Comment by freejoe76** [comment]
Also note that this console error was present as of July, and doesn't appear to have a detrimental effect to any of the addon menu functions.
![screen shot 2018-09-07 at 12 39 04 pm](https://user-images.githubusercontent.com/125554/45231831-76f14b00-b29b-11e8-96d1-cc59260f533d.png)

**Comment by freejoe76** [comment]
Here is what the plugin now looks like, from selection to sidebar to resulting shortcode:

Selection:
![screen shot 2018-09-07 at 12 43 42 pm](https://user-images.githubusercontent.com/125554/45231973-e7986780-b29b-11e8-918d-24b0cd1c321b.png)

Sidebar:
![screen shot 2018-09-07 at 12 43 51 pm](https://user-images.githubusercontent.com/125554/45231988-ee26df00-b29b-11e8-9d18-b7626b170b73.png)

Resulting shortcode:
![screen shot 2018-09-07 at 12 44 38 pm](https://user-images.githubusercontent.com/125554/45232004-f8e17400-b29b-11e8-8a56-2ee945e22195.png)

**Comment by freejoe76** [comment]
The workflow for updating the liveblog addon when there's an existing liveblog addon on the doc is now documented here: https://github.com/nprapps/liveblog-addon#deploying-to-a-google-doc

**Comment by mileswwatkins** [comment]
Also noting this here for the future: Dana will know _ahead of time_ which AP videos we'll have the rights to serve.
