### ISSUE TITLE
Define onlineproduction workflow for live video

### ISSUE THREAD

**Issue by alykat** [nprapps/liveblog#36]
We'll need to get a better handle on exactly how the live video will get to the liveblog.

- Is there a way to get video embed code without embedding the player on a Seamus page? Is a Seamus ID required? If they use the liveblog Seamus ID, does the player have to actually be on the page (embedded in the liveblog doesn't count, b/c that's outside the CMS) for the player to work?
- If we make a shortcode, is there standard markup we can use for the embed and just swap in an ID or some other identifier?
- How do requests for live video usually go through onlineprod?
- How should communication go on election night? (What do they need, what will we need, who will be the points of contact?)

**Comment by freejoe76** [comment]
A. How do requests for live video usually go through onlineprod?

1. Onlineprod gets a feed request from the news desk.
2. AP has a listing of upcoming feeds on its video hub site. Onlineprod clicks the "Book Feed" button
3. There's an elemental box (an AP box) that's transcoding the video that AP delivers to NPR on the Akamai CDN.
4. Once it's in Akamai, there's an asset URL (with a m3u8 extension) that is used to create the embed element in Seamus *or* in jwPlayer for use on NPR network stations.

**Comment by freejoe76** [comment]
C1. If we make a shortcode, is there standard markup we can use for the embed and just swap in an ID or some other identifier?

Yes. The shortcode (which will be built in #35) will most likely look something like `[% apvideo https://content.jwplatform.com/players/7wkxa1LV-5qkQag5F.html %]`

**Comment by mileswwatkins** [comment]
@freejoe76, I forget whether you mentioned earlier today that this was finished; feel free to close if so.

**Comment by freejoe76** [comment]
@mileswwatkins I don't have answers yet on this question, 

> How should communication go on election night? (What do they need, what will we need, who will be the points of contact?)

**Comment by mileswwatkins** [comment]
@freejoe76: Dana is back in the office as of this week. She'll be working ~3 days/wk, but will be available if you want to send email or set up a video chat.

**Comment by freejoe76** [comment]
This document is started here https://docs.google.com/document/d/16cFfbY8Gvn4TCU0FWHYU2k11KRR-RMtYWTHQV9AriRE

**Comment by freejoe76** [comment]
After talking with Dana, these questions need answers:
1. [ ] How do we credential producers for JW Platform?
2. [ ] What's the most number of livestreams that Programming would be able to deliver on election night?
3. [ ] We need documentation on, once a producer is in JW Platform, how to create the livestream.
4. [ ] How do you know when the livestream ends? Who cuts it off?
5. [ ] Does the JW platform auto-archive? That's something that happens in Seamus.

**Comment by mileswwatkins** [comment]
@freejoe76, are these questions for us to answer, or for someone on their editorial desk? And if the latter, what do we need to does our tech team need to do in the meantime, and once those questions are answered? (Basically, what do I need to know once you're outa here?)

**Comment by mileswwatkins** [comment]
From Joe:

Notes from my talk with Angela Alarcon re: live video production workflow:
1. We get a feed request from the news desk
2. AP has a listing of upcoming feeds. We click the "Book Feed" button apvideohub.ap.org/search/
3. After we book a feed we have a box downstairs that via IP TV shows what the feed is.
4. We have an elemental box (an AP box) that's transcoding the video that delivers it to us on our Akamai CDN. elemental3.npr.org
5. SEAMUS: NewStory, add video

**Comment by mileswwatkins** [comment]
Workflow has been defined: DM Product will give a link (the `src` URL from the JW video player's `iframe` element) to the Washington desk, who can then use it in the shortcode; DM's taking on the biggest effort here. I'm doing some follow-up testing of this with Christine Geiger on their CorePublisher staging site, but I think this ticket can be closed.
