### ISSUE TITLE
Check timestamps after DST change

### ISSUE THREAD

**Issue by alykat** [nprapps/liveblog#46]
![image](https://user-images.githubusercontent.com/491318/47223882-46b3c680-d388-11e8-8775-61eb180d3ddc.png)

Also, might be simpler to just say "ET".

**Comment by mileswwatkins** [comment]
These datetimes are rendered by Moment.js, using the users's browser's Internationalization API (supported back to IE 11), so we'll be safe from daylight saving changes!

**Comment by mileswwatkins** [comment]
```
var guessedTimeZone = moment.tz.guess();
moment.tz.setDefault(guessedTimeZone);
```

```
if (moment().format('M D') == moment(lastUpdated).format('M D')) {
    // return regular timestamp
    lastUpdatedTimestamp = moment(lastUpdated).format('h:mm A z');
} else {
    // if from the day before
    lastUpdatedTimestamp = moment(lastUpdated).format('h:mm A z • MMMM D, YYYY');
}
```
