### ISSUE TITLE
Copy-confirmation text is trimmed by the left-hand side of the embed iframe

### ISSUE THREAD

**Issue by mileswwatkins** [nprapps/liveblog#50]
This is happening across several browsers, both mobile and desktop. Maybe we should just move this element a little to the right.

**Comment by mileswwatkins** [comment]
We've had trouble recreating this bug, but try this @goldfarb: macOS Chrome in the Seamus page, with a window width of ~930px.

<img width="133" alt="screen shot 2018-10-29 at 19 05 10" src="https://user-images.githubusercontent.com/4959135/47685654-93c84180-dbad-11e8-88b5-2fc7883c95ca.png">

**Comment by goldfarb** [comment]
![image](https://user-images.githubusercontent.com/3722037/47729093-ec432180-dc35-11e8-9f49-4066f962cf12.png)
(desktop)
![image](https://user-images.githubusercontent.com/3722037/47729112-f533f300-dc35-11e8-861a-837d8f39b8bc.png)
(iOs)

Changed the left margin for the ready to share text
https://github.com/nprapps/liveblog/commit/5add26accc20640eabb276c414dee464347b3f0d
