### ISSUE TITLE
Sharecard description can be truncated by a `<u>` or `<a>`

### ISSUE THREAD

**Issue by mileswwatkins** [nprapps/liveblog#62]
If there's a tag within the first `<p>` of a liveblog post (such as a hyperlink), then its sharecard text will only contain the `<p>`'s contents up until that point.

Eg: https://apps.npr.org/liveblogs/20181106-elections/sharecard/key-ballot-initiatives-to-watch-64.html renders with `<meta name="twitter:description" content="While Washington struggles to find compromise on legislation, there are " />`, since the next words are within a `<u><a>`.

**Comment by thomaswilburn** [comment]
Should be fixed by b409a7a
