### ISSUE TITLE
Make a checklist of TODOs when creating a new liveblog

### ISSUE THREAD

**Issue by alykat** [nprapps/liveblog#64]
Training
Docs
Default share image
Branches
etc

plus links to relevant docs?

**Comment by thomaswilburn** [comment]
I think this doc covers the stuff we should be doing. https://docs.google.com/document/d/1lHyuhAAG_bEuxrzByB8OYkyhjNJ69lhFUhbXJL58W5M/edit# I tend to scan it, when I spin this up, but reading more closely would actually have answered several questions we had last night.

**Comment by alykat** [comment]
One thing to add to that doc, then: a reminder to update the default share image (and where to change that). Joe/Miles added that feature, post-Juan.
